// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	AddSite(ctx context.Context, arg AddSiteParams) (int64, error)
	FindSitesByID(ctx context.Context, id int64) (Site, error)
	ListSites(ctx context.Context) ([]Site, error)
	RemoveSiteByID(ctx context.Context, id int64) (string, error)
	UpdateSitePolled(ctx context.Context, arg UpdateSitePolledParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
