// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
)

const addSite = `-- name: AddSite :one
INSERT INTO sites (name, url) VALUES ($1, $2) returning id
`

type AddSiteParams struct {
	Name string `json:"name"`
	Url  string `json:"url"`
}

func (q *Queries) AddSite(ctx context.Context, arg AddSiteParams) (int64, error) {
	row := q.db.QueryRow(ctx, addSite, arg.Name, arg.Url)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findSiteByID = `-- name: FindSiteByID :one
SELECT id, name, url, created_at, polled_at FROM sites WHERE id = $1
`

func (q *Queries) FindSiteByID(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRow(ctx, findSiteByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.PolledAt,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT
  id, name, url, created_at, polled_at
FROM
  sites
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
			&i.PolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSiteByID = `-- name: RemoveSiteByID :one
DELETE FROM sites WHERE id = $1 returning name
`

func (q *Queries) RemoveSiteByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, removeSiteByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
