// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	FindSitesByID(ctx context.Context, id int64) (Site, error)
	ListSites(ctx context.Context) ([]Site, error)
}

var _ Querier = (*Queries)(nil)
