// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
)

const findSitesByID = `-- name: FindSitesByID :one
SELECT id, name, url, created_at, polled_at FROM sites WHERE id = $1
`

func (q *Queries) FindSitesByID(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRow(ctx, findSitesByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.PolledAt,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT
  id, name, url, created_at, polled_at
FROM
  sites
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
			&i.PolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
