steps:
- name: 'hashicorp/terraform:latest'
  args: ['init']
- name: 'hashicorp/terraform:latest'
  args: ['plan']
- name: 'hashicorp/terraform:latest'
  args: ['apply', '-auto-approve']

options:
  logging: CLOUD_LOGGING_ONLY

